### ISSUE TITLE
asynchronous thread can't be ended properly when the device connection failed

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk#23]
When executing a command, it will create an asynchronous thread to read the data.
However, if the connection failed and throw an connection exception, the thread will not be ended.
In ProtocolHandler.java

    synchronized (transactions) {
      while (!transactions.get(transactionId).isFinished()) {
        try {
          transactions.wait();
        } catch (InterruptedException e) {
          // Exit quietly on break
          return null;
        }
      }
    }

InterruptedException won't be caught if the connection failed

It might cause a memory leak.

**Comment by eb-oss** [comment]
Closing issue; project is being archived.
