### ISSUE TITLE
Zigbee Support 

### ISSUE THREAD

**Issue by karimulla1993** [edgexfoundry/device-sdk#24]
Hi 
Does edgex support Zigbee . If yes what type of Coordinator and Zigbee stack it supports ,where can i find the source code for it.

**Comment by SteveOss** [comment]
@karimulla1993 The trouble with Zigbee is that there isn't a unified Linux stack, so typically dongle vendors provide their own SDKs. Unfortunately his sort of means you need to develop a device service per
Zigbee type (or at least per manufacturer). Do you have a particular device/devices in mind?

**Comment by karimulla1993** [comment]
@SteveOss Is It possible to make generic interface for the coordinators and describe the configuration file(.yml) where one can specify the vendor specific details and according to pull the specific SDK's . I have been working on XBee and TI Zigbee hardware.

**Comment by SteveOss** [comment]
@karimulla1993 Am sure that there are various generic bits of functionality that would be required no matter what the driver used. Is hard to say how much this is without actually doing an implementation. With your experience of XBee and the TI stack, how much functionality/code was common between them?

**Comment by eb-oss** [comment]
Closing issue; project is being archived.
